package com.entities;
// Generated Jun 28, 2017 5:07:51 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Block generated by hbm2java
 */
public class Block  implements java.io.Serializable {


     private int id;
     private Serializable blockName;
     private Serializable description;
     private boolean active;
     private Set<SubjectOfBlock> subjectOfBlocks = new HashSet<SubjectOfBlock>(0);

    public Block() {
    }

	
    public Block(int id, Serializable blockName, boolean active) {
        this.id = id;
        this.blockName = blockName;
        this.active = active;
    }
    public Block(int id, Serializable blockName, Serializable description, boolean active, Set<SubjectOfBlock> subjectOfBlocks) {
       this.id = id;
       this.blockName = blockName;
       this.description = description;
       this.active = active;
       this.subjectOfBlocks = subjectOfBlocks;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getBlockName() {
        return this.blockName;
    }
    
    public void setBlockName(Serializable blockName) {
        this.blockName = blockName;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set<SubjectOfBlock> getSubjectOfBlocks() {
        return this.subjectOfBlocks;
    }
    
    public void setSubjectOfBlocks(Set<SubjectOfBlock> subjectOfBlocks) {
        this.subjectOfBlocks = subjectOfBlocks;
    }




}


