package com.entities;
// Generated Jun 28, 2017 5:07:51 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private int id;
     private Serializable locationName;
     private int priority;
     private Set<University> universities = new HashSet<University>(0);

    public Location() {
    }

	
    public Location(int id, Serializable locationName, int priority) {
        this.id = id;
        this.locationName = locationName;
        this.priority = priority;
    }
    public Location(int id, Serializable locationName, int priority, Set<University> universities) {
       this.id = id;
       this.locationName = locationName;
       this.priority = priority;
       this.universities = universities;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(Serializable locationName) {
        this.locationName = locationName;
    }
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }
    public Set<University> getUniversities() {
        return this.universities;
    }
    
    public void setUniversities(Set<University> universities) {
        this.universities = universities;
    }




}


