package com.entities;
// Generated Jun 28, 2017 5:07:51 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * MajorGroup generated by hbm2java
 */
public class MajorGroup  implements java.io.Serializable {


     private int id;
     private Integer majorTypeId;
     private Serializable majorGroupName;
     private Integer displayOrder;
     private Serializable majorCodePrefix1;
     private Serializable majorCodePrefix2;
     private Serializable majorCodePrefix3;
     private Serializable majorCodePrefix4;
     private Serializable description;
     private Boolean active;
     private Set<Major> majors = new HashSet<Major>(0);

    public MajorGroup() {
    }

	
    public MajorGroup(int id) {
        this.id = id;
    }
    public MajorGroup(int id, Integer majorTypeId, Serializable majorGroupName, Integer displayOrder, Serializable majorCodePrefix1, Serializable majorCodePrefix2, Serializable majorCodePrefix3, Serializable majorCodePrefix4, Serializable description, Boolean active, Set<Major> majors) {
       this.id = id;
       this.majorTypeId = majorTypeId;
       this.majorGroupName = majorGroupName;
       this.displayOrder = displayOrder;
       this.majorCodePrefix1 = majorCodePrefix1;
       this.majorCodePrefix2 = majorCodePrefix2;
       this.majorCodePrefix3 = majorCodePrefix3;
       this.majorCodePrefix4 = majorCodePrefix4;
       this.description = description;
       this.active = active;
       this.majors = majors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getMajorTypeId() {
        return this.majorTypeId;
    }
    
    public void setMajorTypeId(Integer majorTypeId) {
        this.majorTypeId = majorTypeId;
    }
    public Serializable getMajorGroupName() {
        return this.majorGroupName;
    }
    
    public void setMajorGroupName(Serializable majorGroupName) {
        this.majorGroupName = majorGroupName;
    }
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }
    
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
    public Serializable getMajorCodePrefix1() {
        return this.majorCodePrefix1;
    }
    
    public void setMajorCodePrefix1(Serializable majorCodePrefix1) {
        this.majorCodePrefix1 = majorCodePrefix1;
    }
    public Serializable getMajorCodePrefix2() {
        return this.majorCodePrefix2;
    }
    
    public void setMajorCodePrefix2(Serializable majorCodePrefix2) {
        this.majorCodePrefix2 = majorCodePrefix2;
    }
    public Serializable getMajorCodePrefix3() {
        return this.majorCodePrefix3;
    }
    
    public void setMajorCodePrefix3(Serializable majorCodePrefix3) {
        this.majorCodePrefix3 = majorCodePrefix3;
    }
    public Serializable getMajorCodePrefix4() {
        return this.majorCodePrefix4;
    }
    
    public void setMajorCodePrefix4(Serializable majorCodePrefix4) {
        this.majorCodePrefix4 = majorCodePrefix4;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Set<Major> getMajors() {
        return this.majors;
    }
    
    public void setMajors(Set<Major> majors) {
        this.majors = majors;
    }




}


