package com.entities;
// Generated Jun 28, 2017 5:07:51 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject  implements java.io.Serializable {


     private int id;
     private SubjectType subjectType;
     private Serializable subjectName;
     private Serializable description;
     private Boolean active;
     private Set<SubjectOfBlock> subjectOfBlocks = new HashSet<SubjectOfBlock>(0);

    public Subject() {
    }

	
    public Subject(int id) {
        this.id = id;
    }
    public Subject(int id, SubjectType subjectType, Serializable subjectName, Serializable description, Boolean active, Set<SubjectOfBlock> subjectOfBlocks) {
       this.id = id;
       this.subjectType = subjectType;
       this.subjectName = subjectName;
       this.description = description;
       this.active = active;
       this.subjectOfBlocks = subjectOfBlocks;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public SubjectType getSubjectType() {
        return this.subjectType;
    }
    
    public void setSubjectType(SubjectType subjectType) {
        this.subjectType = subjectType;
    }
    public Serializable getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(Serializable subjectName) {
        this.subjectName = subjectName;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Set<SubjectOfBlock> getSubjectOfBlocks() {
        return this.subjectOfBlocks;
    }
    
    public void setSubjectOfBlocks(Set<SubjectOfBlock> subjectOfBlocks) {
        this.subjectOfBlocks = subjectOfBlocks;
    }




}


