package com.entities;
// Generated Jun 28, 2017 5:07:51 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * SubjectType generated by hbm2java
 */
public class SubjectType  implements java.io.Serializable {


     private int id;
     private Serializable subjectTypeName;
     private Serializable description;
     private boolean active;
     private Set<Subject> subjects = new HashSet<Subject>(0);

    public SubjectType() {
    }

	
    public SubjectType(int id, boolean active) {
        this.id = id;
        this.active = active;
    }
    public SubjectType(int id, Serializable subjectTypeName, Serializable description, boolean active, Set<Subject> subjects) {
       this.id = id;
       this.subjectTypeName = subjectTypeName;
       this.description = description;
       this.active = active;
       this.subjects = subjects;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getSubjectTypeName() {
        return this.subjectTypeName;
    }
    
    public void setSubjectTypeName(Serializable subjectTypeName) {
        this.subjectTypeName = subjectTypeName;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set<Subject> getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set<Subject> subjects) {
        this.subjects = subjects;
    }




}


