package com.entities;
// Generated Jun 28, 2017 5:07:51 PM by Hibernate Tools 4.3.1



/**
 * SubjectOfBlock generated by hbm2java
 */
public class SubjectOfBlock  implements java.io.Serializable {


     private int id;
     private Block block;
     private Subject subject;
     private Integer subjectCoefficient;
     private Boolean active;

    public SubjectOfBlock() {
    }

	
    public SubjectOfBlock(int id) {
        this.id = id;
    }
    public SubjectOfBlock(int id, Block block, Subject subject, Integer subjectCoefficient, Boolean active) {
       this.id = id;
       this.block = block;
       this.subject = subject;
       this.subjectCoefficient = subjectCoefficient;
       this.active = active;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Block getBlock() {
        return this.block;
    }
    
    public void setBlock(Block block) {
        this.block = block;
    }
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }
    public Integer getSubjectCoefficient() {
        return this.subjectCoefficient;
    }
    
    public void setSubjectCoefficient(Integer subjectCoefficient) {
        this.subjectCoefficient = subjectCoefficient;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }




}


