package com.entities;
// Generated Jun 28, 2017 5:07:51 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * University generated by hbm2java
 */
public class University  implements java.io.Serializable {


     private int id;
     private Location location;
     private Serializable universityName;
     private Serializable phoneNumber;
     private Serializable email;
     private Serializable website;
     private Serializable logoUrl;
     private int priority;
     private Serializable description;
     private Boolean active;
     private Serializable code;
     private Integer educationLevel;
     private Set<Major> majors = new HashSet<Major>(0);

    public University() {
    }

	
    public University(int id, int priority) {
        this.id = id;
        this.priority = priority;
    }
    public University(int id, Location location, Serializable universityName, Serializable phoneNumber, Serializable email, Serializable website, Serializable logoUrl, int priority, Serializable description, Boolean active, Serializable code, Integer educationLevel, Set<Major> majors) {
       this.id = id;
       this.location = location;
       this.universityName = universityName;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.website = website;
       this.logoUrl = logoUrl;
       this.priority = priority;
       this.description = description;
       this.active = active;
       this.code = code;
       this.educationLevel = educationLevel;
       this.majors = majors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Serializable getUniversityName() {
        return this.universityName;
    }
    
    public void setUniversityName(Serializable universityName) {
        this.universityName = universityName;
    }
    public Serializable getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(Serializable phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Serializable getWebsite() {
        return this.website;
    }
    
    public void setWebsite(Serializable website) {
        this.website = website;
    }
    public Serializable getLogoUrl() {
        return this.logoUrl;
    }
    
    public void setLogoUrl(Serializable logoUrl) {
        this.logoUrl = logoUrl;
    }
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Serializable getCode() {
        return this.code;
    }
    
    public void setCode(Serializable code) {
        this.code = code;
    }
    public Integer getEducationLevel() {
        return this.educationLevel;
    }
    
    public void setEducationLevel(Integer educationLevel) {
        this.educationLevel = educationLevel;
    }
    public Set<Major> getMajors() {
        return this.majors;
    }
    
    public void setMajors(Set<Major> majors) {
        this.majors = majors;
    }




}


